var age = 20;
console.log(age);
age = true;
console.log(age);
age = "Hello World";
console.log(age);
var mixed = [];
mixed.push(5);
mixed.push("Hello");
mixed.push(true);
mixed.push(2.36);
console.log(mixed);
var ninja;
ninja = { name: "Hasindu", age: 20 };
console.log(ninja);
ninja = { name: 25, age: "Hasindu" };
console.log(ninja);
